CREATE TABLE petshop (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    tipo_pet VARCHAR(50) NOT NULL,
    nome_pet VARCHAR (100) NOT NULL,
    idade INTEGER NOT NULL,
    data_nasc DATE NOT NULL,
    data_entrada DATE DEFAULT SYSDATE,
   
    CONSTRAINT petshop_id PRIMARY KEY (id)
);


DROP TABLE petshop;


SELECT * FROM petshop WHERE data_nasc = TO_DATE('14/03/2014', 'DD/MM/YYYY');